### ISSUE TITLE
Multi-Arch Issues with AWS CLI

### ISSUE THREAD

**Issue by sethfduke** [crossplane-contrib/function-shell#23]
# Feature Request

## What problem are you facing?
- When running function-shell on ARM-based nodes, calls to the AWS CLI installed in the function fail, because the Dockerfile for this function only installs the x86 version of the AWS CLI.

## How could this Function help solve your problem?
- Update the Dockerfile and build pipelines to install the appropriate aws-cli based on the arch

**Comment by stevendborrelli** [comment]
closing due to PR #25
